[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["J Leadbetter <j@jleadbetter.com>"]
description = "The Rust Book: Chapter 1.2"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
